import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main overview sidebar - shows top-level categories
  tutorialSidebar: [
    'overview',
    {
      type: 'link',
      label: 'Android SDK',
      href: '/docs/android-sdk/getting-started',
    },
    {
      type: 'category',
      label: 'Tutorial - Basics',
      link: {
        type: 'generated-index',
        title: 'Tutorial - Basics',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/tutorial-basics',
        keywords: ['tutorial', 'basics', 'getting-started'],
      },
      collapsed: false,
      items: [
        'tutorial-basics/create-a-page',
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/markdown-features',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/congratulations',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      link: {
        type: 'generated-index',
        title: 'Tutorial - Extras',
        description: 'Explore advanced Docusaurus features and learn how to extend your documentation site!',
        slug: '/category/tutorial-extras',
        keywords: ['tutorial', 'advanced', 'extras'],
      },
      collapsed: false,
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
  ],

  // Android SDK sidebar - separate section like Docusaurus API docs
  androidSidebar: [
    {
      type: 'autogenerated',
      dirName: 'android-sdk',
    },
  ],
};

export default sidebars;
